try{
    let a = 0;
    console.log(sufiyan)
    console.log("Program ran successfully")
}catch(error){
    console.log("Some error occured...")
    //Lets throw error in catch. so that you can understand purpose of finally
    console.log(Ahmad)
}finally{
    console.log("I am finally & will always execute...")

    // close the file.
    // exit loop.
    //write to the log file...
}